version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/training/circleci-test
    
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/training/circleci-test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: node index.js

workflows:
  version: 2
  
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build