version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/training/circleci-test
    steps:
      - checkout
      - run: npm install

  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/training/circleci-test
    steps:
      - checkout
      - run: node index.js

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build